# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Masonry所有API学习' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Masonry所有API学习

  target 'Masonry所有API学习Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Masonry所有API学习UITests' do
    inherit! :search_paths
    # Pods for testing
  end
pod 'Masonry', '~> 1.0.1'
end
